# Generated by Django 3.2 on 2021-05-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuserstatus',
            name='status',
            field=models.IntegerField(choices=[(0, 'REQUEST'), (1, 'MEMBER'), (2, 'DENIED')], default=0),
        ),
    ]
