# Generated by Django 3.2 on 2021-05-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210504_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Birth_Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
