# Generated by Django 3.2 on 2021-05-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_users_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Birth_Date',
            field=models.DateField(),
        ),
    ]
