# Generated by Django 3.2 on 2021-05-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_users_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Birth_Date',
            new_name='BirthDate',
        ),
    ]
